#Descripcion : Busca el rol por el id
#Parametro   : id (Int)
#Salida      : Rol buscado por el id.
#Example     : http://192.185.36.179/services/?BC=globalmx_roles&id=1
globalmx_roles:
    method: get
    app: controller
    module: ControllerRol
    action: getRolById
#Descripcion : Busca todos los paises 
#Parametro   : No
#Salida      : Todos los paises en la base de datos.
#Example     : http://192.185.36.179/services/?BC=globalmx_pais
globalmx_pais:
	method: get
	app: controller
	module: ControllerPais
	action: getAllPais
#Descripcion : Busca la region
#Parametro   : idPais (Int)
#Salida      : Todos las regiones del id del pais
#Example     : http://192.185.36.179/services/?BC=globalmx_regionbypais&idPais=53
globalmx_regionbypais:
	method: get
	app: controller
	module: ControllerRegion
	action: getRegionByPais
#Descripcion : Obtiene la ciudad dentro de una region
#Parametro   : idRegion (Int)
#Salida      : Lista de ciudades dentro de una region
#Example     : http://192.185.36.179/services/?BC=globalmx_ciudadbyregion&idRegion=3680
globalmx_ciudadbyregion:
	method: get
	app: controller
	module: ControllerCiudad
	action: getCiudadByRegion
#Descripcion : Permite validar si una tarjeta se encuentra en la base de datos
#			   Y el pin concuerda con la tarjeta, Es el primer paso para autenticar.
#Parametro   : numTarjeta
#			   numPin
#Salida      : Da Acceso al modulo de Activaci칩n de tarjeta.
#Example     : http://192.185.36.179/services/?BC=globalmx_activetarjetastep1&numTarjeta=1886934616765905&numPin=5476
globalmx_activetarjetastep1:
	method: post
	app: controller
	module: ControllerTarjeta
	action: activeTarjetaStep1
#Descripcion : Permite crear una persona y asociarle un numero de tarjeta
#			   Es el paso #2 para activar la tarjeta
#Parametro   : cedula
#			   tarjeta
#			   ciudad
#			   nombre
#			   apellido
#			   direccion
#			   barrio
#			   telefono
#			   celular
#			   email
#			   fecha_nacimiento
#			   pin
#Salida      : Respuesta de Exito, Tarjeta activada.
#Example     :http://192.185.36.179/services/?BC=globalmx_activetarjetastep2&cedula=3242&tarjeta=1886934616766151&ciudad=10&nombre=asdas&apellido=asd&direccion=asdsaasdas&barrio=asdsa&telefono=23223&celular=342343&email=asdas&fecha_nacimiento=2015/03/03&pin=6733
globalmx_activetarjetastep2:
	method: post
	app: controller
	module: ControllerPersona
	action: createPersona
#Descripcion : Permite si el usuario existe en la base de datos y concuerda con
#			   la contrase침a. 
#Parametro   : user (String)
#			   password (String)
#Salida      : Da Acceso a la aplicaci칩n de administraci칩n global max
#Example     : http://192.185.36.179/services/?BC=globalmx_v4lidateuser&user=admin&password=admin
globalmx_v4lidateuser:
	method: get
	app: controller
	module: ControllerUsuario
	action: validateUser
#Descripcion : Permite crear un usuario en la base de datos.
#Parametro   : rol    int()
#              cedula int()
#              user   String
#              contrasena String
#Salida      : Retorna mensaje de Exito o Error segun caso cumplido.
#Example     : http://192.185.36.179/services/?BC=globalmx_cr3ateuser&rol=1&cedula=112321321&user=juandavid&pass=twixtwix
globalmx_cr3ateuser:
	method: get
	app: controller
	module: ControllerUsuario
	action: createUser
#Descripcion : Permite eliminar un usuario en la base de datos.
#Parametro   : id    int()
#Salida      : Retorna mensaje de Exito o Error segun caso cumplido.
#Example     : http://192.185.36.179/services/?BC=globalmx_d3let3user&id=1
globalmx_d3let3user:
	method: get
	app: controller
	module: ControllerUsuario
	action: deleteUser
#Descripcion : Permite listar todos los usurios de la base de datos
#Parametro   : No tiene parametros de entrada
#Salida      : Retorna todos los usuarios
#Example     : http://192.185.36.179/services/?BC=globalmx_l1stuser
globalmx_l1stuser:
	method: get
	app: controller
	module: ControllerUsuario
	action: listUser
#Descripcion : Permite listar todos los usurios de la base de datos por ID
#Parametro   : id (int)
#Salida      : Si encuentra el usuario lo retorna
#Example     : http://192.185.36.179/services/?BC=globalmx_l1stuserby1d&id=1
globalmx_l1stuserby1d:
	method: get
	app: controller
	module: ControllerUsuario
	action: listUserById
#Descripcion : Permite actualizar el usuario
#Parametro   : 
#Salida      : Mensaje de exito si actualiza el usuario.
#Example     : http://192.185.36.179/services/?BC=globalmx_upd4teuser&rol=1&cedula=112321321&user=juandavid&pass=twixtwix
globalmx_upd4teuser:
	method: get
	app: controller
	module: ControllerUsuario
	action: updateUser
#Descripcion : Permite crear el menu de AppGlobalMax
#Parametro   : rol    int()
#              cedula int()
#              user   String
#              contrasena String
#Salida      : Retorna mensaje de Exito o Error segun caso cumplido.
#Example     : http://192.185.36.179/services/?BC=globalmx_menu&documento=13
globalmx_menu:
	method: get
	app: controller
	module: ControllerMenu
	action: getMenu
#Descripcion : Permite consultar tarjetas por numero o por estados
#Parametro   : numTarjeta (int)
#              estado (int)
#Salida      : Si no ingresa numTarjeta ni estado : Lista todas las tarjetas
#              Si no ingresa numTarjeta y estado : Lista todas las tarjetas segun el estado
#              Si ingresa numTarjeta : Muestra la tarjeta con el numero si existe.
#Example     : http://192.185.36.179/services/?BC=globalmx_gettarjeta&nit=805009514&trama=503
globalmx_gettarjeta:
	method: get
	app: controller
	module: ControllerTarjeta
	action: consultaTarjeta
#Descripcion : Servicio core que permite realizar transacciones.
#Parametro   : tarjeta (int)
#              nit     (int)
#              trama   (String)
#              valor   (int)
#              punto   (int)
#Salida      : Si se realiza una recarga retorna : Transaccion Exitosa.
#			   Si se realiza una compra retorna : Compra Exitosa.
#              Si no se puede realizar la transaccion retorna : Error en la transaccion.
#Example     : http://192.185.36.179/services/?BC=globalmxt1&tarjeta=1886934616766149&valor=999999&nit=805009514&punto=23&trama=503
globalmxt1:
	method: get
	app: controller
	module: ControllerTarjeta
	action: managerTransation
#Descripcion : Servicio core que permite consulta el tipo de transaccion
#Parametro   : tarjeta (int)
#              nit     (int)
#              trama   (String)
#Salida      : Valida si la tarjeta ya fue comprada y esta lista para transaccion retorna : 2
#              Valida si la tarjeta no a sido comprada para realizar la compra retorna : 1
#Example     : http://192.185.36.179/services/?BC=globalmxt2&tarjeta=1886934616766149&nit=805009514&trama=503
globalmxt2:
	method: get
	app: controller
	module: ControllerTarjeta
	action: tipoTransation
#Descripcion : Permite crear tarjetas
#Parametro   : numero    (bigint)(20)
#              estado    (int)(11)
#              usuario   (bigint)(11)
#              precio    (bigint)(20)
#              vendedor  (int)(11)
#              impresion ((int)(11)
#              precio (bigint)
#Salida      : Retorna mensaje de exito si la tarjeta fue creada
#Example     : http://192.185.36.179/services/?BC=globalmx_createtarjeta&numero=9999999999999999&estado=2&usuario=1&precio=45000&vendedor=1&impresion=4
globalmx_createtarjeta:
	method: get
	app: controller
	module: ControllerTarjeta
	action: createTarjeta
#Descripcion : Permite modificar las tarjetas
#Parametro   : numero    (bigint)(20)
#              estado    (int)(11)
#              usuario   (bigint)(11)
#              precio    (bigint)(20)
#              vendedor  (int)(11)
#              impresion ((int)(11)
#              precio (bigint)
#Salida      : Retorna mensaje de exito si la tarjeta fue modificada
#Example     : http://192.185.36.179/services/?BC=globalmx_updatetarjeta&numero=9999999999999999&precio=10000&usuario=1&estado=3&vendedor=2&impresion=1
globalmx_updatetarjeta:
	method: get
	app: controller
	module: ControllerTarjeta
	action: updateTarjeta
#Descripcion : Permite crear empresas
#Parametro   : nit    	  int(11)
#              nombre     varchar(45) 
#              direccion  varchar(45)
#              telefono   int(11) 
#              ip  		  varchar(45)
#              trama 	  varchar(45)
#Salida      : Retorna mensaje de exito si la empresa fue creada
#Example     : http://192.185.36.179/services/?BC=globalmx_createempresa&nit=123123&nombre=Baloto&direccion=calle1&telefono=1231232&ip=192.250.0.21&trama=321
globalmx_createempresa:
	method: get
	app: controller
	module: ControllerEmpresa
	action: createEmpresa
#Descripcion : Permite actualizar empresas
#Parametro   : nit    	  int(11)
#              nombre     varchar(45) 
#              direccion  varchar(45)
#              telefono   int(11) 
#              ip  		  varchar(45)
#              trama 	  varchar(45)
#Salida      : Retorna mensaje de exito si la empresa fue modificada
#Example     : http://192.185.36.179/services/?BC=globalmx_updateempresa&nit=123123&nombre=Baloto&direccion=calle1&telefono=1231232&ip=192.250.0.21&trama=321
globalmx_updateempresa:
	method: get
	app: controller
	module: ControllerEmpresa
	action: updateEmpresa
#Descripcion : Permite listar todas las empresas
#Parametro   : No tiene parametros de entrada
#Salida      : Retorna todas las empresas en que se encuentran en la base de datos
#Example     : http://192.185.36.179/services/?BC=globalmx_listempresa
globalmx_listempresa:
	method: get
	app: controller
	module: ControllerEmpresa
	action: listEmpresa
#Descripcion : Permite crear pines
#Parametro   : numero    bigint(20) 
#              codigo    varchar(45)
#Salida      : Retorna mensaje de exito si el pin fue creado
#Example     : http://192.185.36.179/services/?BC=globalmx_createpin&numero=1886934616761159&codigo=6666
globalmx_createpin:
	method: get
	app: controller
	module: ControllerPin
	action: createPin
#Descripcion : Permite actualizar pines
#Parametro   : idPin        bigint(20)
#              numero       bigint(20) 
#              codigo       varchar(45)
#              vencimiento  date
#Salida      : Retorna mensaje de exito si el pin fue modificada
#Example     : http://192.185.36.179/services/?BC=globalmx_updatepin&numero=1886934616761160&idPin=5001
globalmx_updatepin:
	method: get
	app: controller
	module: ControllerPin
	action: updatePin
#Descripcion : Permite listar todas los pines
#Parametro   : No tiene parametros de entrada
#Salida      : Retorna todos los pines en que se encuentran en la base de datos
#Example     : http://192.185.36.179/services/?BC=globalmx_listpin
globalmx_listpin:
	method: get
	app: controller
	module: ControllerPin
	action: listPin
#Descripcion : Permite crear estados
#Parametro   : descripcion    varchar(45)
#Salida      : Retorna mensaje de exito si el estado fue creado
#Example     : http://192.185.36.179/services/?BC=globalmx_createestado&descripcion=Prueba
globalmx_createestado:
	method: get
	app: controller
	module: ControllerEstado
	action: createEstado
#Descripcion : Permite actualizar estados
#Parametro   : idEstado        int(11)
#              descripcion     varchar(45)
#Salida      : Retorna mensaje de exito si el estado fue modificada
#Example     : http://192.185.36.179/services/?BC=globalmx_updateestado&idEstado=5&descripcion=Prueba2
globalmx_updateestado:
	method: get
	app: controller
	module: ControllerEstado
	action: updateEstado
#Descripcion : Permite listar todas los estados
#Parametro   : No tiene parametros de entrada
#Salida      : Retorna todos los estados  que se encuentran en la base de datos
#Example     : http://192.185.36.179/services/?BC=globalmx_listestado
globalmx_listestado:
	method: get
	app: controller
	module: ControllerEstado
	action: listEstado
#Descripcion : Permite crear impresiones
#Parametro   : codigo 		  varchar(4)
#			   descripcion    varchar(100)
#Salida      : Retorna mensaje de exito si la impresion fue creada
#Example     : http://192.185.36.179/services/?BC=globalmx_createimpresion&codigo=PRUE&descripcion=Prueba
globalmx_createimpresion:
	method: get
	app: controller
	module: ControllerImpresion
	action: createImpresion
#Descripcion : Permite actualizar estados
#Parametro   : idEstado        int(11)
#              descripcion     varchar(45)
#Salida      : Retorna mensaje de exito si el estado fue modificada
#Example     : http://192.185.36.179/services/?BC=globalmx_updateimpresion&idglobalmxImpresion=5&codigo=PR&descripcion=Prueba2
globalmx_updateimpresion:
	method: get
	app: controller
	module: ControllerImpresion
	action: updateImpresion
#Descripcion : Permite listar todas las impresiones
#Parametro   : No tiene parametros de entrada
#Salida      : Retorna todos las impresiones  que se encuentran en la base de datos
#Example     : http://192.185.36.179/services/?BC=globalmx_listimpresion
globalmx_listimpresion:
	method: get
	app: controller
	module: ControllerImpresion
	action: listImpresion