## YAML Template.
service_getallroles:
    method: get
    app: controller
    module: ControllerRol
    action: getRolById

service_getallpais:
	method: get
	app: controller
	module: ControllerPais
	action: getAllPais